### ISSUE TITLE
Lightweight app/build.gradle

### ISSUE THREAD

**Issue by IliaEremin** [ravidsrk/android-mvp-starter#13]
Two tips:
1. Move lint configuration to xml file.
2. Move dependencies to separate file. See example: https://gist.github.com/IlyaEremin/31338c25bc6c9503d0f7e0d419696876

Motivation: build.gradle is high level application setup file. It should contain only high level logic, like "take proguard rules from here", "take lint rules there". Otherwise it's hard to read.

**Comment by ravidsrk** [comment]
@IlyaEremin Can you open a PR for the same?

**Comment by IliaEremin** [comment]
sure, WIP

**Comment by IliaEremin** [comment]
@ravidsrk review plz
