### ISSUE TITLE
Broken imports in yo android-mvp-starter bundle

### ISSUE THREAD

**Issue by basudz365** [ravidsrk/android-mvp-starter#17]
Created a new project using yo android-mvp-starter and ran into some issues with a broken imports. 

data/remote/MvpStarterServiceFactory
It still has an import for com.jakewharton.retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory
which should be importing retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory instead

util/NetworkUtil
has import for com.jakewharton.retrofit2.adapter.rxjava2.HttpException
which should be retrofit2.HttpException

Looks to be fixed in the source code here, just needs an update in the yeoman bundle.

**Comment by ravidsrk** [comment]
@basudz365 Thanks for pointing out. I have updated the yeoman bundle now 👍 You should be able get the updated module now.

**Comment by ravidsrk** [comment]
@basudz365 Please use yeoman module v1.3.5.

**Comment by basudz365** [comment]
@ravidsrk I fixed it locally, just wanted to point it out since I was testing out your setup here..which is very nice by the way, so thanks for sharing!!

**Comment by ravidsrk** [comment]
@basudz365 Thanks, Let me know your feedback/improvements on the whole project? You can also open an PR if you have something cool 👍
