### ISSUE TITLE
Could not read script '/path/to/project/app/dependencies.gradle' as it does not exist.

### ISSUE THREAD

**Issue by dassiorleando** [ravidsrk/android-mvp-starter#18]
Hi guys,
First Thanks for this great tool for generating Android project.

**I'm new on it and just generate one project and face error when building it in command line and also via Android Studio**

That is the output:

> FAILURE: Build failed with an exception.

* Where:
Build file '/path/to/project/app/build.gradle' line: 98

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/path/to/project/app/dependencies.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**BUILD FAILED**

Don't know how to bypass it, please.
Thanks in advance.

**Comment by ravidsrk** [comment]
@dassiorleando I have updated the generator with the fix. Please update the generator to version 1.4.0. It should resolve the problem.

**Comment by dassiorleando** [comment]
Ok understood, Thanks.
