### ISSUE TITLE
Errors when opening the generated project in Android Studio 2.3.3

### ISSUE THREAD

**Issue by ptrahan** [ravidsrk/android-mvp-starter#30]
Hello,

It seems the generated project is not compatible with Android Studio 2.3.3. Error is:

Android Gradle plugin 3.0.0-alpha5 must not be applied to project {project path} since version 3.0.0-alpha5 was already applied to this project.

After modifying build.gradle to use:
classpath 'com.android.tools.build:gradle:2.3.3' instead, I got more errors.

**Comment by ravidsrk** [comment]
@ptrahan 
As the README says, this project is being done on Android Studio 3.0 and above. I have no plans to lower that.

**Comment by ptrahan** [comment]
I think it should be stated on your github page as this is important information. Android Studio 3 is still in beta and a lot of (if not most) people are using the stable version. You could provide a slightly modified gradle script for those using the stable Android Studio version, no need to lower the whole project. Anyway, I'm just suggesting. Thanks. (by the way I could not find it in the readme.md)
