### ISSUE TITLE
Unable to inject SharedPreferences.

### ISSUE THREAD

**Issue by alex-berdnikov** [ravidsrk/android-mvp-starter#32]
PreferencesHelper is not actually used anywhere in the project so the app compiles just fine, but try to inject it or SharedPreferences anywhere and you'll get compilation error:

Error:(22, 17) error: android.content.SharedPreferences cannot be provided without an @Provides-annotated method.
android.content.SharedPreferences is injected at...

**Comment by divadvo** [comment]
How did you solve this problem? I have the same issue..

**Comment by alex-berdnikov** [comment]
Hi, to be honest I don't remember it already :)
But I may suggest you check if you use right Context scope.

**Comment by divadvo** [comment]
PR #31 solves this.
Specifically this change:

>
https://github.com/androidstarters/android-starter/blob/efaa89994bb59eb25a1e255b4b4ef642ed29f63c/app/src/main/java/io/mvpstarter/sample/injection/module/AppModule.java#L34-L38

>
https://github.com/androidstarters/android-starter/pull/31/files#diff-12d90704750c0430abb5b207e0f529e6L33
